export {
  fetchAcademicOverviewFromDb,
  fetchAllDataFromDb,
  fetchUniversitiesFromDb,
  saveUniversityToDb,
  deleteUniversityFromDb,
  fetchProfessorsFromDb,
  saveProfessorToDb,
  deleteProfessorFromDb,
  fetchSubjectsFromDb,
  saveSubjectToDb,
  deleteSubjectFromDb,
  fetchSchedulesFromDb,
  saveScheduleToDb,
  deleteScheduleFromDb,
  fetchDeliverablesFromDb,
  saveDeliverableToDb,
  deleteDeliverableFromDb,
  fetchSyllabusTopicsFromDb,
  saveSyllabusTopicToDb,
  deleteSyllabusTopicFromDb,
} from '../lib/db/repository-pg';
